targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
      artemis:
        options:
          fragments_glob: lib/graphql/fragment/**/*.fragment.graphql
          schema_mapping:
            - output: lib/graphql/generated/graphql_api.dart
              naming_scheme: pathedWithFields
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/queries_glob/**/*.graphql
          scalar_mapping:
            - graphql_type: JSON
              dart_type: Map<String, dynamic>
            - graphql_type: Date
              dart_type: DateTime
              use_custom_parser_import: true
              custom_parser_import: "package:mpp/graphql/coercers.dart"
            - graphql_type: DateTime
              dart_type: DateTime
              use_custom_parser_import: true
              custom_parser_import: "package:mpp/graphql/coercers.dart"
            - graphql_type: URL
              dart_type: String
            - graphql_type: Longitude
              dart_type: double
            - graphql_type: Latitude
              dart_type: double
            - graphql_type: EmailAddress
              dart_type: String
            - graphql_type: ID
              dart_type: int
              use_custom_parser_import: true
              custom_parser_import: "package:mpp/graphql/coercers.dart"
            - graphql_type: Upload
              custom_parser_import: "package:factory/graphql/coercers.dart"
              dart_type:
                name: MultipartFile
                imports:
                  - "package:http/http.dart"
